apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/kubernetesproject-470408/backend:latest   # replace PROJECT_ID
          ports:
            - containerPort: 8080
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS
            - name: DB_HOST
              value: "10.107.16.4"   # Cloud SQL private IP
            - name: DB_PORT
              value: "5432"
            - name: JWT_SECRET   # 👈 NEW
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
