apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/kubernetesproject-470408/frontend:latest   # replace PROJECT_ID
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_URL
              value: "http://backend-service"
            - name: FLASK_SECRET   # 👈 NEW
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: FLASK_SECRET
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
