apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
stringData:
  DB_NAME: todos          # change if your DB name is different
  DB_USER: postgres       # or your custom DB user
  DB_PASS: "Majed1234!"   # <-- put the real password here
