name: CI/CD to GKE

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: kubernetesproject-470408
  
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      k8s_changed: ${{ steps.filter.outputs.k8s }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            k8s:
              - 'k8s/**'

  backend:
    needs: filter
    if: needs.filter.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Build & Push Backend
        run: |
          IMAGE="gcr.io/kubernetesproject-470408/backend:latest"
          docker build -t $IMAGE ./backend
          docker push $IMAGE
      - name: Update Backend Deployment
        run: kubectl rollout restart deployment backend

  frontend:
    needs: filter
    if: needs.filter.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Build & Push Frontend
        run: |
          IMAGE="gcr.io/kubernetesproject-470408/frontend:latest"
          docker build -t $IMAGE ./frontend
          docker push $IMAGE
      - name: Update Frontend Deployment
        run: kubectl rollout restart deployment frontend

  k8s:
    needs: filter
    if: needs.filter.outputs.k8s_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Apply k8s manifests
        run: kubectl apply -f k8s/
